### ISSUE TITLE
ImportError: cannot import name 'UnencryptedCookieSessionFactoryConfig'

### ISSUE THREAD

**Issue by moldach** [Lornatang/FSRCNN-PyTorch#1]
I'm running into an error on `Ubuntu 20.04 LTS` trying to run the `test_image.py` script:

```
$ python --version
Python 3.6.0
```

## Error

```
(base) mtg@mtg-ThinkPad-P53:~/bin/FSRCNN-PyTorch$ python test_image.py --file ./assets/baby.png --weights ./weights/fsrcnn_4x.pth --upscale-factor 4
Traceback (most recent call last):
  File "test_image.py", line 20, in <module>
    from apex import amp
  File "/home/mtg/.pyenv/versions/3.6.0/lib/python3.6/site-packages/apex/__init__.py", line 13, in <module>
    from pyramid.session import UnencryptedCookieSessionFactoryConfig
ImportError: cannot import name 'UnencryptedCookieSessionFactoryConfig'
```

## `pip freeze`

```
(base) mtg@mtg-ThinkPad-P53:~/bin/FSRCNN-PyTorch$ pip freeze
absl-py==0.11.0
acronym==2.0.0
AMP==1.1.4
anykeystore==0.2
apex==0.9.10.dev0
appdirs==1.4.3
asgiref==3.3.1
astor==0.8.1
astunparse==1.6.3
attrs==19.3.0
bamsnap==0.2.17
bar-chart-race==0.1.0
cachetools==4.2.1
caldav==0.1.4
certifi==2020.12.5
cffi==1.14.0
chardet==4.0.0
click==7.1.2
conditional==1.3
coverage==5.5
cryptacular==1.5.5
cycler==0.10.0
defusedxml==0.7.1
distlib==0.3.1
Django==3.1.5
docopt==0.6.2
filelock==3.0.12
flatbuffers==1.12
gast==0.2.2
genomeview==1.0.1
glitch-this==1.0.2
gmpy==1.17
google-auth==1.24.0
google-auth-oauthlib==0.4.2
google-pasta==0.2.0
greenlet==1.0.0
grpcio==1.32.0
h5py==2.10.0
hupper==1.10.2
idna==2.10
image==1.5.33
imageio==2.9.0
importlib-metadata==1.6.1
importlib-resources==5.1.0
jedi==0.17.2
Jinja2==2.11.2
joblib==1.0.0
jsonschema==2.6.0
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.2
kiwisolver==1.3.1
lineedit==0.1.5
lxml==4.6.2
Markdown==3.3.3
MarkupSafe==1.1.1
matplotlib==3.3.4
mitywgs==0.2.1
mlt==0.3.0
mongoengine==0.23.0
more-itertools==8.4.0
nltk==3.5
nose==1.3.7
numpy==1.19.5
oauthlib==3.1.0
opencv-python==4.5.1.48
opt-einsum==3.3.0
packaging==16.8
pandas==0.25.3
parso==0.7.1
PasteDeploy==2.1.1
pbkdf2==1.3
Pillow==8.1.0
plaster==1.0
plaster-pastedeploy==0.7
pluggy==0.13.1
progressbar2==3.53.1
protobuf==3.14.0
py==1.8.2
pyasn1==0.4.8
pyasn1-modules==0.2.8
pybind11==2.5.0
pycparser==2.20
pyfaidx==0.5.8
pyfastx==0.8.2
Pygments==2.7.4
pymongo==3.11.3
pyparsing==2.2.0
pyramid==2.0
pyramid-mailer==0.15.1
pysam==0.16.0
pytabix==0.1
pytest==5.4.3
python-dateutil==2.8.1
python-utils==2.5.6
python3-openid==3.2.0
pytz==2018.5
PyVCF==0.6.8
PyYAML==5.4.1
radian==0.5.10
rchitect==0.3.30
regex==2020.11.13
repoze.sendmail==4.4.1
requests==2.25.1
requests-oauthlib==1.3.0
rpy2==3.3.3
rsa==4.7
scipy==1.5.4
seqlib==0.0.6
sewar==0.4.4
six==1.15.0
SQLAlchemy==1.4.1
sqlparse==0.4.1
svviz2==2.0a3
tabulate==0.8.9
tensorboard==2.0.2
tensorboard-plugin-wit==1.8.0
tensorboardX==2.1
tensorflow-estimator==2.0.1
tensorflow-gpu==2.0.0
termcolor==1.1.0
torch==1.4.0+cu100
torchvision==0.5.0+cu100
tqdm==4.46.1
transaction==3.0.1
translationstring==1.4
trapify==0.1.2
typing-extensions==3.7.4.3
tzlocal==2.1
UNKNOWN==0.0.0
urllib3==1.26.3
vape==0.1.1
velruse==1.1.1
venusian==3.0.0
virtualenv==20.4.2
vobject==0.9.6.1
watchdog==2.0.2
wcwidth==0.2.4
WebOb==1.8.7
Werkzeug==1.0.1
wrapt==1.12.1
WTForms==2.3.3
wtforms-recaptcha==0.3.2
xerox==0.4.1
XlsxWriter==1.3.7
zalgotext==0.2.0
zc.buildout==2.13.3
zipp==3.1.0
zope.deprecation==4.4.0
zope.interface==5.2.0
zope.sqlalchemy==1.3
```

Any idea what could be going wrong?

**Comment by Lornatang** [comment]
Upgrade Torch>=1.7.0
Because built in apex function.
```python3
# Example
import torch.cuda.amp as amp
```

**Comment by moldach** [comment]
Tried upgrading to `torch>=1.7.0` but the problem persists (although I can call `import torch.cuda.amp as amp` from within the interpreter):

```
$ pip install --upgrade torch
$ python
Python 3.6.3 (default, Mar 16 2021, 18:11:00) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch.cuda.amp as amp
>>>
```

However, when I try to run the script again I'm met with the same error:

```
$ python test_image.py --file ./assets/baby.png --weights ./weights/fsrcnn_4x.pth --upscale-factor 4
Traceback (most recent call last):
  File "test_image.py", line 20, in <module>
    import apex
ModuleNotFoundError: No module named 'apex'

```

Does anything else need to be upgraded?

## `pip freeze`
```
(venv) mtg@mtg-ThinkPad-P53:~/bin/FSRCNN-PyTorch$ pip freeze
cffi==1.11.5
cloudpickle==0.5.3
cycler==0.10.0
dask==0.18.2
dataclasses==0.8
decorator==4.3.0
face-alignment==1.3.3
imageio==2.3.0
kiwisolver==1.0.1
llvmlite==0.36.0
matplotlib==2.2.2
networkx==2.1
numba==0.53.0
numpy==1.19.5
opencv-python==4.5.1.48
pandas==0.23.4
Pillow==5.2.0
pycparser==2.18
pygit==0.1
pyparsing==2.2.0
python-dateutil==2.7.3
pytz==2018.5
PyWavelets==1.1.1
PyYAML==5.1
scikit-image==0.17.2
scikit-learn==0.19.2
scipy==1.1.0
six==1.11.0
tifffile==2020.9.3
toolz==0.9.0
torch==1.8.0
torchvision==0.2.1
tqdm==4.24.0
typing-extensions==3.7.4.3
```

**Comment by Lornatang** [comment]
@moldach Thank you very much for your attention to this project library. This library was written in version 1.5.0, and the apex library was cloned and installed. I'll give you a link, or you wait for my next version update?

**Comment by Lornatang** [comment]
@moldach  https://github.com/NVIDIA/apex For installation Apex for Python
